name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.20.4]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Print Node.js version
      run: node --version

    - name: Print npm version
      run: npm --version

    - name: Install dependencies
      run: npm i
      shell: bash
      timeout-minutes: 10

    - name: Build the project
      run: npm run build
      shell: bash
